name: potemkin
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - matplotlib
  - jupyter
  - jupyterlab
  - notebook
  - ipykernel
  - ipywidgets
  - pytorch
  - torchvision
  - transformers
  - datasets
  - accelerate
  - huggingface_hub
  - tokenizers
  - openai
  - requests
  - beautifulsoup4
  - lxml
  - openpyxl
  - pyyaml
  - tqdm
  - pillow
  - nbconvert
  - nbformat
  - jupyter_contrib_nbextensions
  - jupyter_nbextensions_configurator
  - setuptools
  - wheel
  - certifi
  - urllib3
  - charset-normalizer
  - idna
  - pydantic
  - jinja2
  - markupsafe
  - packaging
  - six
  - pytz
  - python-dateutil
  - decorator
  - attrs
  - jsonschema
  - pygments
  - traitlets
  - prompt-toolkit
  - wcwidth
  - parso
  - jedi
  - executing
  - pure_eval
  - stack_data
  - asttokens
  - matplotlib-inline
  - platformdirs
  - typing_extensions
  - filelock
  - fsspec
  - sympy
  - mpmath
  - networkx
  - regex
  - safetensors
  - dill
  - multiprocess
  - pyarrow
  - cffi
  - pycparser
  - defusedxml
  - entrypoints
  - mistune
  - pandocfilters
  - bleach
  - tinycss2
  - webencodings
  - jupyterlab_pygments
  - send2trash
  - terminado
  - prometheus_client
  - argon2-cffi
  - argon2-cffi-bindings
  - websocket-client
  - jupyter_server
  - jupyter_client
  - jupyter_core
  - jupyter_events
  - jupyter-lsp
  - jupyterlab_server
  - notebook-shim
  - nbclient
  - nbclassic
  - debugpy
  - psutil
  - tornado
  - pyzmq
  - nest-asyncio
  - python-json-logger
  - rfc3986-validator
  - rfc3339-validator
  - python-fastjsonschema
  - jsonschema-specifications
  - referencing
  - rpds-py
  - comm
  - widgetsnbextension
  - jupyterlab_widgets
  - qtconsole
  - qtpy
  - sniffio
  - anyio
  - httpcore
  - httpx
  - h11
  - aiohttp
  - aiosignal
  - frozenlist
  - multidict
  - yarl
  - aiohappyeyeballs
  - annotated-types
  - async-lru
  - brotli-python
  - overrides
  - distro
  - et_xmlfile
  - joblib
  - threadpoolctl
  - bottleneck
  - numexpr
  - soupsieve
  - pydantic-core
  - jiter
  - python-xxhash
  - babel
  - pip:
    - jupyter_highlight_selected_word
    - jupyter_latex_envs
